server:
  port: 8080
  servlet:
    context-path: /overlook-hotel

spring:
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none

app:
  maxStayInDays: 3
  maxReserveInAdvance: 30
  suggestionRange: 5