server:
  port: 8080
  servlet:
    context-path: /overlook-hotel

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/overlook-hotel
    username: redrum
    password: redrum123
    initialize: true
  jpa:
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: true
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update